function SaveCalibrationResults(directory, leftImages, rightImages, ...
    usedImages, model, errors, optionDisplayImages, ...
    optionSaveImages)
% Undistorts images using the camera model defined by cameraParameters.
% 
% :param directory: string, path to the output directory.
% :param leftImages: ImageDatastore, the left images.
% :param rightImages: ImageDatastore, the right images.
% :param usedImages: boolean array, the images used for calibration.
% :param model: stereoParameters, the stereo camera model.
% :param errors: stereoEstimationErrors, the estimation errors.
% :param optionDisplay: bool, display image option.

%% Create output directory.
if ~exist(directory, "dir")
    mkdir(directory);
end

%% Save images.
WriteImagesToFile(directory, leftImages, rightImages, usedImages, ...
    model, optionDisplayImages, optionSaveImages);

%% Save camera parameters.
fprintf('\n - Saving parameters...');

% Camera intrinsics.
WriteIntrinsicsToFile( ...
    strcat(directory, 'Intrinsic-Parameters-Left.txt'), ...
    model.CameraParameters1.Intrinsics, ...
    errors.Camera1IntrinsicsErrors);
WriteIntrinsicsToFile( ...
    strcat(directory, 'Intrinsic-Parameters-Right.txt'), ...
    model.CameraParameters2.Intrinsics, ...
    errors.Camera2IntrinsicsErrors);

% Stereo extrinsics.
WriteExtrinsicsToFile(strcat(directory, 'Extrinsic-Parameters.txt'), ...
    model, errors);

%% Save reprojection, extrinsic, and calibration target statistics.
fprintf('\n - Saving statistics...\n');

[leftReprojectionStats, leftExtrinsicsStats, targetCoordinates] = ...
    ExtractCalibrationStatistics(model.CameraParameters1);
[rightReprojectionStats, rightExtrinsicStats, ~] = ...
    ExtractCalibrationStatistics(model.CameraParameters2);

% .
extrinsicErrors = errors.Camera1ExtrinsicsErrors;
extrinsicErrorStats = array2table([ ...
    (1:length(extrinsicErrors.TranslationVectorsError))' ...
    extrinsicErrors.TranslationVectorsError, ...
    extrinsicErrors.RotationVectorsError ]);

extrinsicErrorStats.Properties.VariableNames = [ "Index", ...
    "TranslationErrorX" , "TranslationErrorY", "TranslationErrorZ", ...
    "RotationErrorX", "RotationErrorY", "RotationErrorZ" ];

writetable(extrinsicErrorStats, ...
    strcat(directory, "Extrinsic-Errors-Left.csv"));
writetable(targetCoordinates, ...
    strcat(directory, "Calibration-Target.csv"));
writetable(leftReprojectionStats, ...
    strcat(directory, 'Reprojection-Statistics-Left.csv'));
writetable(rightReprojectionStats, ...
    strcat(directory, 'Reprojection-Statistics-Right.csv'));
writetable(leftExtrinsicsStats, ...
    strcat(directory, 'Extrinsic-Statistics-Left.csv'));
writetable(rightExtrinsicStats, ...
    strcat(directory, 'Extrinsic-Statistics-Right.csv'));
end